title: From the Mayflower to the Midwest
description: Konecny & Wood Family History — living research archive
# Use an official GitHub Pages remote theme (no Gemfile needed)
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Useful site-wide settings
timezone: America/New_York
markdown: kramdown

# Add simple header navigation
# These files must exist at the site root.
header_pages:
  - index.md
  - outline/index.md
  - research/index.md
  - sources/index.md

# Collections you can grow into over time
collections:
  people:
    output: true
    permalink: /people/:title/
  lines:
    output: true
    permalink: /lines/:title/
  notes:
    output: true
    permalink: /notes/:title/